export enum ErrorTypes {
	OBJECT_NOT_FOUND_ERROR = "OBJECT_NOT_FOUND_ERROR",
	OBJECT_UN_DEFINED_ERROR = "OBJECT_UN_DEFINED_ERROR",
	EMAIL_ERROR = "EMAIL_ERROR",
	TYPE_ERROR = "TYPE_ERROR",
	REQUIRED_ERROR = "REQUIRED_ERROR",
	INVALID_REFERAL_CODE = "INVALID_REFERAL_CODE"
}